Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -14,3 +14,6 @@ jobs:
       - name: Run a one-line script
         # gets run in the shell
         run: echo "Hello, world!"
+        
+      - name: Simulate an error
+        run: echo "About to fail"; exit 1
